[versions]
agp = "8.11.2"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
codeScanner = "2.3.0"
core = "3.5.3"
activity = "1.11.0"
constraintlayout = "2.2.1"
gson = "2.13.2"
qrgenerator = "1.0.4"
qrgeneratorVersion = "1.0.1"
okapibarcode = "0.5.2"
androidsvgAar = "1.4"
androidImageCropper = "4.6.0"
recyclerview = "1.4.0"
cardview = "1.0.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
code-scanner = { group = "com.github.yuriy-budiyev", name = "code-scanner", version.ref = "codeScanner" }
core = { group = "com.google.zxing", name = "core", version.ref = "core" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
qrgenerator = { group = "com.github.androidmads", name = "QRGenerator", version.ref = "qrgenerator" }
androidmads-qrgenerator = { group = "com.github.androidmads", name = "QRGenerator", version.ref = "qrgeneratorVersion" }
okapibarcode = { group = "uk.org.okapibarcode", name = "okapibarcode", version.ref = "okapibarcode" }
androidsvg-aar = { group = "com.caverock", name = "androidsvg-aar", version.ref = "androidsvgAar" }
android-image-cropper = { group = "com.vanniktech", name = "android-image-cropper", version.ref = "androidImageCropper" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
cardview = { group = "androidx.cardview", name = "cardview", version.ref = "cardview" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

